# SPDX-FileCopyrightText: Copyright 2023 Gloria G.
# SPDX-License-Identifier: BSD-2-Clause

[workspace]
members  = [
    "engine/core",

    "engine/modules/shell",
    "engine/modules/vulkan",

    "title"
]

resolver = "2"
