# SPDX-FileCopyrightText: Copyright 2023 Gloria G.
# SPDX-License-Identifier: BSD-2-Clause^

[build]
rustflags = ["-Adead_code"]

[source.crates-io]
replace-with = "vendored"

[source.vendored]
directory = "ThirdParty"
