// SPDX-FileCopyrightText: Copyright 2023 Gloria G.
// SPDX-License-Identifier: BSD-2-Clause

use crate::ffi::{PhysicalDeviceFeatures, VK_FALSE, VK_TRUE};

pub const DEVICE_FEATURES: PhysicalDeviceFeatures = PhysicalDeviceFeatures {
    robust_buffer_access: VK_FALSE,
    full_draw_index_uint32: VK_TRUE,
    image_cube_array: VK_FALSE,
    independent_blend: VK_TRUE,
    geometry_shader: VK_TRUE,
    tessellation_shader: VK_TRUE,
    sample_rate_shading: VK_FALSE,
    dual_src_blend: VK_FALSE,
    logic_op: VK_TRUE,
    multi_draw_indirect: VK_FALSE,
    draw_indirect_first_instance: VK_FALSE,
    depth_clamp: VK_TRUE,
    depth_bias_clamp: VK_FALSE,
    fill_mode_non_solid: VK_TRUE,
    depth_bounds: VK_FALSE,
    wide_lines: VK_TRUE,
    large_points: VK_FALSE,
    alpha_to_one: VK_FALSE,
    multi_viewport: VK_TRUE,
    sampler_anisotropy: VK_TRUE,
    texture_compression_etc2: VK_FALSE,
    texture_compression_astc_ldr: VK_FALSE,
    texture_compression_bc: VK_FALSE,
    occlusion_query_precise: VK_FALSE,
    pipeline_statistics_query: VK_FALSE,
    vertex_pipeline_stores_and_atomics: VK_FALSE,
    fragment_stores_and_atomics: VK_FALSE,
    shader_tessellation_and_geometry_point_size: VK_FALSE,
    shader_image_gather_extended: VK_FALSE,
    shader_storage_image_extended_formats: VK_FALSE,
    shader_storage_image_multisample: VK_FALSE,
    shader_storage_image_read_without_format: VK_FALSE,
    shader_storage_image_write_without_format: VK_FALSE,
    shader_uniform_buffer_array_dynamic_indexing: VK_FALSE,
    shader_sampled_image_array_dynamic_indexing: VK_FALSE,
    shader_storage_buffer_array_dynamic_indexing: VK_FALSE,
    shader_storage_image_array_dynamic_indexing: VK_FALSE,
    shader_clip_distance: VK_FALSE,
    shader_cull_distance: VK_FALSE,
    shader_float64: VK_TRUE,
    shader_int64: VK_TRUE,
    shader_int16: VK_TRUE,
    shader_resource_residency: VK_FALSE,
    shader_resource_min_lod: VK_FALSE,
    sparse_binding: VK_FALSE,
    sparse_residency_buffer: VK_FALSE,
    sparse_residency_image_2d: VK_FALSE,
    sparse_residency_image_3d: VK_FALSE,
    sparse_residency_2_samples: VK_FALSE,
    sparse_residency_4_samples: VK_FALSE,
    sparse_residency_8_samples: VK_FALSE,
    sparse_residency_16_samples: VK_FALSE,
    sparse_residency_aliased: VK_FALSE,
    variable_multisample_rate: VK_FALSE,
    inherited_queries: VK_FALSE,
};
